name: "Run tests"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        helmfile-version:
          - "v0.157.0"
          - "v0.158.0"
          - "v0.158.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Kube in Docker
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
    
      - name: Setup Helmfile
        uses: mamezou-tech/setup-helmfile@v1.3.0
        with:
          helmfile-version: ${{ matrix.helmfile-version }}
      
      - name: Run Helmfile
        run: |
          cd test-directory
          helmfile diff
